%% show the significance percentile for roi V1
total=sum(spect_ave_sig(:,:,roi_V1),3);
figure(1);subplot(4,2,1);
a=nanmean(spect_pixel_wise_cond5(:,:,roi_V1),3);
b=nanmean(a(:,1:8),2); 
c=std(a(:,1:8),0,2);
[spect_ave_sig_V1]=calculate_significance_for_spectogram(a,b,c);
imagesc(spect_ave_sig_V1);colorbar(mapgeog);title('significance for averaging over pixels');
subplot(4,2,2);
per=find(total>0);
x=zeros(64,223);
x(per)=ones(size(per));
imagesc(x);colorbar(mapgeog);title('1 pixel at least is significant');
subplot(4,2,3);
per=find(total>size(roi_V1,1)*0.5);
x=zeros(64,223);
x(per)=ones(size(per));
imagesc(x);colorbar(mapgeog);title('50% of the pixels at least are significant');
subplot(4,2,4);
per=find(total>size(roi_V1,1)*0.55);
x=zeros(64,223);
x(per)=ones(size(per));
imagesc(x);colorbar(mapgeog);title('55% of the pixels at least are significant');
subplot(4,2,5);
per=find(total>size(roi_V1,1)*0.6);
x=zeros(64,223);
x(per)=ones(size(per));
imagesc(x);colorbar(mapgeog);title('60% of the pixels at least are significant');
subplot(4,2,6);
per=find(total>size(roi_V1,1)*0.65);
x=zeros(64,223);
x(per)=ones(size(per));
imagesc(x);colorbar(mapgeog);title('65% of the pixels at least are significant');
subplot(4,2,7);
per=find(total>size(roi_V1,1)*0.70);
x=zeros(64,223);
x(per)=ones(size(per));
imagesc(x);colorbar(mapgeog);title('70% of the pixels at least are significant');
subplot(4,2,8);
per=find(total>size(roi_V1,1)*0.80);
x=zeros(64,223);
x(per)=ones(size(per));
imagesc(x);colorbar(mapgeog);title('80% of the pixels at least are significant');

%% show the significance percentile for roi V2
total=sum(spect_ave_sig(:,:,roi_V2),3);
figure(2);subplot(4,2,1);
a=nanmean(spect_pixel_wise_cond5(:,:,roi_V2),3);
b=nanmean(a(:,1:8),2); 
c=std(a(:,1:8),0,2);
[spect_ave_sig_V2]=calculate_significance_for_spectogram(a,b,c);
imagesc(spect_ave_sig_V2);colorbar(mapgeog);title('significance for averaging over pixels');
subplot(4,2,2);
per=find(total>0);
x=zeros(64,223);
x(per)=ones(size(per));
imagesc(x);colorbar(mapgeog);title('1 pixel at least is significant');
subplot(4,2,3);
per=find(total>size(roi_V2,1)*0.5);
x=zeros(64,223);
x(per)=ones(size(per));
imagesc(x);colorbar(mapgeog);title('50% of the pixels at least are significant');
subplot(4,2,4);
per=find(total>size(roi_V2,1)*0.55);
x=zeros(64,223);
x(per)=ones(size(per));
imagesc(x);colorbar(mapgeog);title('55% of the pixels at least are significant');
subplot(4,2,5);
per=find(total>size(roi_V2,1)*0.6);
x=zeros(64,223);
x(per)=ones(size(per));
imagesc(x);colorbar(mapgeog);title('60% of the pixels at least are significant');
subplot(4,2,6);
per=find(total>size(roi_V2,1)*0.65);
x=zeros(64,223);
x(per)=ones(size(per));
imagesc(x);colorbar(mapgeog);title('65% of the pixels at least are significant');
subplot(4,2,7);
per=find(total>size(roi_V2,1)*0.70);
x=zeros(64,223);
x(per)=ones(size(per));
imagesc(x);colorbar(mapgeog);title('70% of the pixels at least are significant');
subplot(4,2,8);
per=find(total>size(roi_V2,1)*0.80);
x=zeros(64,223);
x(per)=ones(size(per));
imagesc(x);colorbar(mapgeog);title('80% of the pixels at least are significant');

%% show the significance percentile for roi V4
total=sum(spect_ave_sig(:,:,roi_V4),3);
figure(3);subplot(4,2,1);
a=nanmean(spect_pixel_wise_cond5(:,:,roi_V4),3);
b=nanmean(a(:,1:8),2); 
c=std(a(:,1:8),0,2);
[spect_ave_sig_V4]=calculate_significance_for_spectogram(a,b,c);
imagesc(spect_ave_sig_V4);colorbar(mapgeog);title('significance for averaging over pixels');
subplot(4,2,2);
per=find(total>0);
x=zeros(64,223);
x(per)=ones(size(per));
imagesc(x);colorbar(mapgeog);title('1 pixel at least is significant');
subplot(4,2,3);
per=find(total>size(roi_V4,1)*0.5);
x=zeros(64,223);
x(per)=ones(size(per));
imagesc(x);colorbar(mapgeog);title('50% of the pixels at least are significant');
subplot(4,2,4);
per=find(total>size(roi_V4,1)*0.55);
x=zeros(64,223);
x(per)=ones(size(per));
imagesc(x);colorbar(mapgeog);title('55% of the pixels at least are significant');
subplot(4,2,5);
per=find(total>size(roi_V4,1)*0.6);
x=zeros(64,223);
x(per)=ones(size(per));
imagesc(x);colorbar(mapgeog);title('60% of the pixels at least are significant');
subplot(4,2,6);
per=find(total>size(roi_V4,1)*0.65);
x=zeros(64,223);
x(per)=ones(size(per));
imagesc(x);colorbar(mapgeog);title('65% of the pixels at least are significant');
subplot(4,2,7);
per=find(total>size(roi_V4,1)*0.70);
x=zeros(64,223);
x(per)=ones(size(per));
imagesc(x);colorbar(mapgeog);title('70% of the pixels at least are significant');
subplot(4,2,8);
per=find(total>size(roi_V4,1)*0.80);
x=zeros(64,223);
x(per)=ones(size(per));
imagesc(x);colorbar(mapgeog);title('80% of the pixels at least are significant');